model:
  rating_set: [1, 2, 3, 4, 5]
  embedding_dim: 64
  user_feature_dim: 5
  item_feature_dim: 10
  dropout_rate: 0.1

optimizer:
  class: Adam
  lr: 0.001
  weight_decay: 0.000000015

sampler:
  fanout: 3

data:
  mlog_data_path: data/test/test_dump

train:
  n_epoch: 2
  batch_size: 100
  device: [cuda:0, cuda:1]
